# Generated by Django 5.0.6 on 2024-06-11 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationTab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'вкладка публикаций',
                'verbose_name_plural': 'вкладки публикаций',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(verbose_name='Заголовок')),
                ('link', models.URLField(verbose_name='Ссылка')),
                ('image', models.FileField(upload_to='publications/', verbose_name='Изображение')),
                ('tab', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publications.publicationtab', verbose_name='Вкладка')),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'публикации',
            },
        ),
    ]
